core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('tasks/',include('tasks.urls',namespace='tasks')),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns =[
    path('',views.index, name='index'),
    #CRUD OPERATIONS BEGIN HERE
    path('<int:task_id>/',views.task_detail, name='detail'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('login/',views.ilogin, name='login'),
    path('register/', views.iregister, name='register')
]

tasks/models.py
from django.db import models
#from django.contrib.auth import get_user_model
# Create your models here.

#User = get_user_model()
class Tasks(models.Model):
    #user        = models.OneToOneField(User, on_delete=models.CASCADE)
    title       = models.CharField(max_length=50, blank=False)  
    description = models.TextField(blank=False )        
    due_date    = models.DateField(blank=True) 
    date_created= models.DateTimeField(blank=False)    
    """A status field to be added. Down here"""
    #status      = models.BooleanField(default='in progress')   
    CATEGORY_CHOICES = [
        ('General', 'General'),
        ('Personal', 'Personal'),
        ('Work', 'Work'),
    ]

    categories = models.CharField(
        max_length=20, 
        choices=CATEGORY_CHOICES,
        default='General'
    )
    PRIORITY_CHOICES = [
        ('High', 'High'),
        ('Medium', 'Medium'),
        ('Low', 'Low'),
    ]

    priority = models.CharField(
        max_length=20, 
        choices=PRIORITY_CHOICES,
        default='Medium'
    )

    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name_plural = 'Tasks' 

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager,PermissionsMixin
# Create your models here.

class myUserManager(BaseUserManager):
    def create_user(self,username,email,password=None, **extra_fields):
        if not username:
            raise ValueError('The username field must be included')
        if not email:
            raise ValueError('Email must be provided')
        
        username = self.model.normalize_username(username)
        email = self.normalize_email(email)

        extra_fields.pop( 'email' , None)
        user= self.model(username= username,email=email, **extra_fields)
        user.set_password(password)
        user.save(using = self._db)
        return user
    
    def create_superuser(self,username,email,password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser',True)

        return self.create_user(username,email, password, **extra_fields)
    
class myUser(AbstractBaseUser,PermissionsMixin):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active =models.BooleanField(default= True)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects= myUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Tasks
from django.contrib import messages
from django.utils import timezone
from datetime import datetime
# Create your views here.
def index(request):
    if request.method == 'POST':
        title       = request.POST.get('title')
        description = request.POST.get('description')
        categories  = request.POST.get('categories') 
        due_date    = request.POST.get('due_date')  
        priority    = request.POST.get('priority') 
        print(due_date)
        if not title:
            messages.error(request, f'Title must be added')
        if not description:
            messages.error(request, f'Description must be added')
        if not due_date:
            messages.error(request, f'Due date must be added')
        try:
            # Convert mm/dd/yy format to YYYY-MM-DD format
            due_date = datetime.strptime(due_date, '%Y-%m-%d')

            # now = timezone.now().replace(tzinfo=None)

            if due_date.date() < timezone.now().date():
                raise ValueError('Due date must be a future date.')

        except ValueError as e:
            if 'future date' in str(e):
                messages.error(request, str(e))
            else:
                messages.error(request, 'Invalid date format. Use YYYY-MM-DD format.')
            return redirect('tasks:index')
        date_created = timezone.now()

        Tasks.objects.create(
            title = title,
            description = description,
            due_date = due_date,
            categories = categories,
            priority = priority,
            date_created = date_created,
        )
        tasks = Tasks.objects.all()
        messages.success(request, f'Task added successfully.')
        # return render (request, 'tasks/index.html', {'tasks':tasks})
        return redirect('tasks:index')
    tasks = Tasks.objects.all()
    return render(request, 'tasks/index.html', {'tasks': tasks})

"""CRUD OPERATIONS"""
#read operations
def task_detail(request, task_id):
    task = get_object_or_404(Tasks,id=task_id)
    return render(request, 'tasks/task_detail.html', {'task':task})




"""END OF CRUD OPERATIONS"""

users/views.py
from django.shortcuts import render,redirect, get_object_or_404
from . models import myUser
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.http import Http404
from django.urls import reverse
# Create your views here.

"""Start of user authentication"""
def iregister(request):
    if request.method == 'POST':
        #take in details from the html / frontend
        username    = request.POST['username'] 
        email       = request.POST['email']
        pass1       = request.POST['pass1']
        pass2       = request.POST['pass2']

        if pass1 != pass2:
            messages.error(request, 'Passwords don\'t match. Try again')
            return render(request, 'users/register.html')
        
        #check for existing email
        if myUser.objects.filter(email=email).exists():
            messages.error(request,'A user with a siliar email exists. Try another.')
            return render(request, 'users/register.html')
        
        #check for existing username
        if myUser.objects.filter(username=username).exists():
            messages.error(request,'A user with a similar username exists. Try another.')
            return render(request, 'users/register.html')

        user= myUser.objects.create(
            username = username,
            email    =email,
        )
        user.set_password(pass1)
        user.is_active = True 
        user.save()
        return redirect ('login') #when user creates acc successfully they are redirected to the login page
    
    return render(request, 'users/register.html')


def ilogin(request):
    if request.method == 'POST':
        username    = request.POST['username']
        pass1       = request.POST['pass1']

        try:
            get_object_or_404(myUser, username= username)
            user = authenticate(request, username = username, pass1 = pass1)
            if user is not None:
                login(request,user)
                messages.success(f'Welcome {username}')
                print('fooo')
                return redirect('index')
            else:
                messages.error(request,'Invalid credentials provided')
        except Http404:
            messages.error(request, f'Account with the username {username} does not exist. CReate account to continue.')
        return render(request, 'users/login.html', {'username': username, 'pass1':pass1})
    else:
        return render (request, 'users/login.html')

def ilogout(request):
    logout(request)
    return redirect( 'login' )
"""End of user authentication"""

templates/tasks/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/unnamed.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
  <h1 class="">My task app</h1>
  <!--  -->
  <div class="container shadow p-3 mb-5 bg-white rounded">
    <div class="card-body">
      <h3 class="card-title mb-3">Enter tasks below</h3>
      {% if messages %}
    <div class="message-dialog" id="msg">
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show {{ message.tags }}" role="alert">
          <span class="icon"></span>
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </div>
  {% endif %}
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-floating mb-3">
        <input type="text" id="floatingInput" name="title" class="form-control" placeholder="Today I want to"><br>
        <label for="title" id="floatingInput">Task title</label>
      </div>
      <div class="form-floating mb-4">
        <textarea class="form-control" value="{{task.description}}" name="description" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
        <label for="floatingTextarea2">Break down the task</label>
      </div>
      <span  class="my-3">   </span>
      <div class="form-floating mb-4">
        <select name="categories" class="form-select" id="floatingSelect" aria-label="Floating label select example">
          <option selecbted>Choose category</option>
          <option value="General">General</option>
          <option value="Personal">Personal</option>
          <option value="Work">Work</option>
        </select>
        <label for="floatingSelect">Assign category below</label>
      </div>
      <div class="form-floating mb-4">
          <input type="date" name="due_date" class="form-control" id="inputDate" >
          <label for="inputDate" class="form-label">When do you want to complete the task?</label><br>
      </div>
      <div class="form-floating mb-4">
        <select name="priority" class="form-select" id="floatingSelect" aria-label="Floating label select example">
          <option value="">Priority</option>
          <option value="High">High</option>
          <option value="Medium">Medium</option>
          <option value="Low">Low</option>
        </select>
        <label for="floatingSelect">Set task priority</label>
      </div>

      <div class="form-floating mb-4 text-center">
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>
    </form>
    </div>
  </div>
</div>
<div class="container shadow p-3 mb-5 bg-white rounded">
    <div class="card-body">
      <!-- <div class="card-body"> -->
        <h5 class="card-title mb-3">Your tasks are here.</h5>
        <!-- Table Variants -->
        <table class="table table-bordered table-hover" id="mytasks">
          <thead>
            <tr>
              <th scope="col">Task title</th>
              <th scope="col">Category</th>
              <th scope="col">Due date</th>
              <th scope="col">Priority</th>
              <th scope="col">Details</th>

            </tr>
          </thead>
          <tbody>
            {% for task in tasks%}
             {% if task.priority == 'High' %}
             <tr class="table-primary">
               <a href="#">
              <th scope="row">{{task.title}}</th></a>
              <td>{{task.categories}}</td>
              <td>{{task.due_date | date:"m/d/y" }}</td>
              <td>{{task.priority}}</td>
              <td><a href="{% url 'tasks:detail' task.id %}">Overview</a></td>
            </tr>
             {% elif task.priority == 'Medium' %}
            <tr class="table-info">
              <th scope="row">{{task.title}}</th>
              <td>{{task.categories}}</td>
              <td>{{task.due_date}}</td>
              <td>{{task.priority}}</td>
              <td><a href="{% url 'tasks:detail' task.id %}">Overview</a></td>
            </tr>
             {% else %}
            <tr class="table-danger">
            <th scope="row">{{task.title}}</th>
            <td>{{task.categories}}</td>
            <td>{{task.due_date}}</td>
            <td>{{task.priority}}</td>
            <td><a href="{% url 'tasks:detail' task.id %}">Overview</a></td>
            </tr>
             {% endif %}
            {% endfor%}
          </tbody>
        </table>
        <!-- End Table Variants -->
      </div>
    <!-- </div> -->
  </div>
    <!-- scripts -->
    <!-- <script>
      $(document).ready(function() {
          // Get today's date
          var today = new Date().toISOString().split('T')[0];
      
          // Set the min attribute of the date input field to today's date
          $('#inputDate').attr('min', today);
      });
      </script>       -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/tasks/task_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/unnamed.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h1 class="">My task app</h1>
    <div class="container shadow p-3 mb-5 bg-white rounded">
    <div class="card">
        <div class="card-body pt-3">
          <!-- Bordered Tabs -->
          <ul class="nav nav-tabs nav-tabs-bordered" role="tablist">

            <li class="nav-item" role="presentation">
              <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview" aria-selected="true" role="tab">Overview</button>
            </li>

            <li class="nav-item" role="presentation">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit" aria-selected="false" role="tab" tabindex="-1">Edit Profile</button>
            </li>

            <li class="nav-item" role="presentation">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings" aria-selected="false" tabindex="-1" role="tab">Settings</button>
            </li>

            <li class="nav-item" role="presentation">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password" aria-selected="false" tabindex="-1" role="tab">Change Password</button>
            </li>

          </ul>
          <div class="tab-content pt-2">

            <div class="tab-pane fade profile-overview active show" id="profile-overview" role="tabpanel">
              <h5 class="card-title">Task description</h5>
              <p class="small fst-italic">{{task.description}}</p>

              <h5 class="card-title">Task details</h5>

              <div class="row">
                <div class="col-lg-3 col-md-4 label ">Title</div>
                <div class="col-lg-9 col-md-8">{{task.title}}</div>
              </div>
              <div class="row">
                <div class="col-lg-3 col-md-4 label ">Category</div>
                <div class="col-lg-9 col-md-8">{{task.categories}}</div>
              </div>
              <div class="row">
                <div class="col-lg-3 col-md-4 label ">Due date</div>
                <div class="col-lg-9 col-md-8">{{task.due_date}}</div>
              </div>
              <div class="row">
                <div class="col-lg-3 col-md-4 label ">Priority</div>
                <div class="col-lg-9 col-md-8">{{task.priority}}</div>
              </div>
            </div>

            <div class="tab-pane fade profile-edit pt-3" id="profile-edit" role="tabpanel">

              <!-- Profile Edit Form -->
              <form>
                <div class="row mb-3">
                  <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                  <div class="col-md-8 col-lg-9">
                    <img src="assets/img/profile-img.jpg" alt="Profile">
                    <div class="pt-2">
                      <a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></a>
                      <a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                    </div>
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Full Name</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="fullName" type="text" class="form-control" id="fullName" value="Kevin Anderson">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="about" class="col-md-4 col-lg-3 col-form-label">About</label>
                  <div class="col-md-8 col-lg-9">
                    <textarea name="about" class="form-control" id="about" style="height: 100px">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</textarea>
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="company" class="col-md-4 col-lg-3 col-form-label">Company</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="company" type="text" class="form-control" id="company" value="Lueilwitz, Wisoky and Leuschke">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Job" class="col-md-4 col-lg-3 col-form-label">Job</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="job" type="text" class="form-control" id="Job" value="Web Designer">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Country" class="col-md-4 col-lg-3 col-form-label">Country</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="country" type="text" class="form-control" id="Country" value="USA">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Address" class="col-md-4 col-lg-3 col-form-label">Address</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="address" type="text" class="form-control" id="Address" value="A108 Adam Street, New York, NY 535022">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Phone" class="col-md-4 col-lg-3 col-form-label">Phone</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="phone" type="text" class="form-control" id="Phone" value="(436) 486-3538 x29071">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="email" type="email" class="form-control" id="Email" value="k.anderson@example.com">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Twitter" class="col-md-4 col-lg-3 col-form-label">Twitter Profile</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="twitter" type="text" class="form-control" id="Twitter" value="https://twitter.com/#">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Facebook" class="col-md-4 col-lg-3 col-form-label">Facebook Profile</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="facebook" type="text" class="form-control" id="Facebook" value="https://facebook.com/#">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Instagram" class="col-md-4 col-lg-3 col-form-label">Instagram Profile</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="instagram" type="text" class="form-control" id="Instagram" value="https://instagram.com/#">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="Linkedin" class="col-md-4 col-lg-3 col-form-label">Linkedin Profile</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="linkedin" type="text" class="form-control" id="Linkedin" value="https://linkedin.com/#">
                  </div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
              </form><!-- End Profile Edit Form -->

            </div>

            <div class="tab-pane fade pt-3" id="profile-settings" role="tabpanel">

              <!-- Settings Form -->
              <form>

                <div class="row mb-3">
                  <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                  <div class="col-md-8 col-lg-9">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="changesMade" checked="">
                      <label class="form-check-label" for="changesMade">
                        Changes made to your account
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="newProducts" checked="">
                      <label class="form-check-label" for="newProducts">
                        Information on new products and services
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="proOffers">
                      <label class="form-check-label" for="proOffers">
                        Marketing and promo offers
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="securityNotify" checked="" disabled="">
                      <label class="form-check-label" for="securityNotify">
                        Security alerts
                      </label>
                    </div>
                  </div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
              </form><!-- End settings Form -->

            </div>

            <div class="tab-pane fade pt-3" id="profile-change-password" role="tabpanel">
              <!-- Change Password Form -->
              <form>

                <div class="row mb-3">
                  <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="password" type="password" class="form-control" id="currentPassword">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="newpassword" type="password" class="form-control" id="newPassword">
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                  <div class="col-md-8 col-lg-9">
                    <input name="renewpassword" type="password" class="form-control" id="renewPassword">
                  </div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Change Password</button>
                </div>
              </form><!-- End Change Password Form -->

            </div>

          </div><!-- End Bordered Tabs -->

        </div>
      </div>
    </div>
</body>
</html>

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<title>Login</title>
	<style>
		.message-dialog {
          position: absolute;
          top: 20%;
          left: 50%;
          transform: translate(-50%, -50%);
          z-index: 9999;
          padding: 20px;
          max-width: auto;
          text-align: center;
        }
        
        .notification {
          background-color: #f8f8f8;
          border: 1px solid #ccc;
          border-radius: 4px;
          padding: 10px;
          margin-bottom: 10px;
          display: flex;
          align-items: center;
        }
        
        .notification.success {
          background-color: #dff0d8;
          border-color: #d6e9c6;
        }
        
        .notification.warning {
          background-color: #fcf8e3;
          border-color: #faebcc;
        }
        
        .notification.error {
          background-color: #f2dede;
          border-color: #ebccd1;
        }
        
        .notification:before {
          font-family: "Arial", sans-serif;
          font-weight: bold;
          font-size: 18px;
          margin-right: 8px;
        }
        
        .notification.success:before {
          content: '\2713';
          color: #3c763d;
        }
        
        .notification.warning:before {
          content: '\26A0';
          color: #8a6d3b;
        }
        
        .notification.error:before {
          content: '\2717';
          color: #a94442;
        }
	</style>
</head>
<body>
	<main>
		<div class="main">
			{% if messages %}
		<div class="message-dialog" id="msg">
		  {% for message in messages %}
			<div class="notification {{ message.tags }}">
			  <span class="icon"></span>
			  {{ message }}
			</div>
		  {% endfor %}
		</div>
		{% endif %}
		<div class="container">
	
		  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
			<div class="container">
			  <div class="row justify-content-center">
				<div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
	
				  <div class="d-flex justify-content-center py-4">
					
				  </div><!-- End Logo -->
	
				  <div class="card mb-3">
					<a href="/"><img src="{% static 'images/unnamed.png' %}" style="width: 5rem;height: 5rem;" /></a>
					<div class="card-body">
	
					  <div class="pt-4 pb-2">
						<h5 class="card-title text-center pb-0 fs-4">Log in to your account</h5>
						<p class="text-center small">Start planning your day</p>
					  </div>
	
					  <form class="row g-3" method="post">
						{% csrf_token %}
						<div class="col-12">
						  <label for="yourName" class="form-label">Your Name</label>
						  <input type="text" name="username" class="form-control" id="yourName" required>
						  <div class="invalid-feedback">Please enter your name!</div>
						</div>
				
	
						<div class="col-12">
						  <label for="yourPassword" class="form-label">Password</label>
						  <input type="password" name="pass1" class="form-control" id="yourPassword" required>
						  <div class="invalid-feedback">Please enter your password!</div>
						</div>
	
	
						<div class="col-12">
						  <div class="form-check">
							<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  							<label class="form-check-label" for="flexCheckDefault">Reveal password</label>
						  </div>
						</div>
						<div class="col-12">
						  <button class="btn btn-success w-100" type="submit">Login now</button>
						</div>
						<div class="col-12">
						  <p class="small mb-0">Don't have an account?Click <a href="{% url 'register' %}">here</a></p>
						</div>
					  </form>
	
					</div>
				  </div>
	
				  <div class="credits">
					<!-- All the links in the footer should remain intact. -->
					<!-- You can delete the links only if you purchased the pro version. -->
					<!-- Licensing information: https://bootstrapmade.com/license/ -->
					<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
					Designed: <a href="https://github.com/keith244/Task-App" target="_blank">Me</a>
				  </div>
	
				</div>
			  </div>
			</div>
	
		  </section>
	
		</div>
	  </main>

	<!-- bootstrap scripts -->
	<script>
		// Wait for the DOM to be fully loaded
		document.addEventListener('DOMContentLoaded', function() {
		  // Select all notification elements
		  var notifications = document.querySelectorAll('.notification');
	  
		  // Iterate over each notification
		  notifications.forEach(function(notification) {
			// Set a timeout to hide each notification after 10 seconds
			setTimeout(function() {
			  notification.style.display = 'none';  // Hide the notification
			}, 1000);  // 10000 milliseconds = 10 seconds
		  });
		});
	  </script>
	  <script>
        document.addEventListener('DOMContentLoaded', function() {
            const passwordField = document.getElementById('yourPassword');
            const checkbox = document.getElementById('flexCheckDefault');

            checkbox.addEventListener('change', function() {
                if (checkbox.checked) {
                    // Show the password
                    passwordField.type = 'text';
                } else {
                    // Hide the password
                    passwordField.type = 'password';
                }
            });
        });
    </script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>